[alias]
# `nestool` doesn't need testing
test-all = ["test", "-p", "nesmur", "-p", "nes"]
test-nes = ["test", "-p", "nes"]
test-gui = ["test", "-p", "nesmur"]

fmt-nes = ["fmt", "-p", "nes"]
fmt-gui = ["fmt", "-p", "nesmur"]
fmt-xtask = ["fmt", "-p", "xtask"]

sys-gen-docs = ["doc", "--no-deps", "--workspace", "--document-private-items", "-Zrustdoc-map"]
docs = ["xtask", "docs"]

xtask = ["run", "-p", "xtask", "-q", "--"]

[doc.extern-map.registries]
crates-io = "https://docs.rs/"
